# Delay between auto-saves in seconds
# Default: 300 (5 minutes)
autosave-delay: 300

# Format for an announcement
announcement:
  task: '%player% has made the advancement &a[%advancement%&a]'
  goal: '%player% has reached the goal &a[%advancement%&a]'
  challenge: '%player% has completed the challenge &5[%advancement%5]'
